version: "3"

services:

  mongodb:
    image: mongo:6.0
    command: mongod --bind_ip_all
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    networks:
      - annales

  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   hostname: postgres
  #   environment:
  #     POSTGRES_PASSWORD: password123
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ../pkg/postgres/base.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ../postgres:/var/lib/postgresql/data
  #   networks:
  #     - annales

networks:
  annales:
    driver: bridge
